### ISSUE TITLE
Refuses to build

### ISSUE THREAD

**Issue by annanuran** [SplittyDev/spotify-rs#4]
In a totally clean project, I've added `spotify = "0.7.1"` to the Cargo.toml, and upon running `cargo build`, I receive 
```
error: failed to run custom build command for `openssl v0.9.24`

Caused by:
  process didn't exit successfully: `/home/eringel/projects/lyricsTUI/target/debug/build/openssl-9d546c3c98d2140a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to detect OpenSSL version', /home/eringel/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
```
I presume this is related to an older version of reqwest being required for the crate? Is there a workaround?

**Comment by SplittyDev** [comment]
Hi, this project is _really_ old and probably has to be updated. I'll check it out in a bit

**Comment by SplittyDev** [comment]
I just updated the library to Rust 2021 edition (all the way back from 2015 😆). It compiles now (tested on `Rust 1.64`) and I've pushed a new version (`0.8.0`).

I'm sorry I took so long to respond to this issue, I'm managing a lot of projects and simply didn't see the notification in time. To be honest, I'm not sure if Spotify still exposes the local API nowadays (I wrote this around 2017).
